"""empty message

Revision ID: 8d8efacfc21f
Revises: d9f55d747c4c
Create Date: 2018-11-09 12:17:48.329740

"""

# revision identifiers, used by Alembic.
revision = '8d8efacfc21f'
down_revision = 'd9f55d747c4c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
