"""empty message

Revision ID: d9f55d747c4c
Revises: 38c4e85512a9
Create Date: 2018-11-09 12:14:02.642594

"""

# revision identifiers, used by Alembic.
revision = 'd9f55d747c4c'
down_revision = '38c4e85512a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
